export const OFFICIAL_RANKS = [
  "Candidate",
  "Assistant Intern",
  "Intern",
  "Senior Intern",
  "Envoy",
  "Senior Envoy",
  "Special Envoy",
  "Dean",
  "Ambassador",
  "Ambassador Extraordinary",
  "Ambassador Plenipotentiary",
];

export const OFFICIAL_ASSOCIATIONS = [
  "Agape Baptist Association",
  "Abeokuta North West Baptist Association",
  "Ketu Baptist Association",
  "Irepodun Oke-Yewa Baptist Association",
  "Zion Baptist Association",
  "Abeokuta South Baptist Association",
  "Ijebu North East Baptist Association",
  "Great Grace Baptist Association",
  "Abeokuta East Baptist Association",
  "Upper Room Baptist Association",
  "Ijebu North Baptist Association",
  "Abeokuta North-East Baptist Association",
  "Abeokuta west Baptist Association",
  "Bethel Baptist Association",
  "Ayetoro Baptist Association",
  "Dominion Baptist Association",
  "Iroyin Ayo Baptist Association",
  "Ijebu Central Baptist Association",
  "Rehoboth Baptist Association",
  "Christlife Baprist Association",
  "Ifeoluwa Baptist Association",
  "Ijebu Progressive Baptist Association",
  "Yewa Baptist Association",
  "Ayooluwa Baptist Association",
  "Macedonia Baptist Association",
];
